### ISSUE TITLE
bug(mobile): Info not expanding correctly

### ISSUE THREAD

**Issue by broth68** [gw2ocs/gw2achievements#4]
**Screenshot**
![20201026_011603.jpg](https://user-images.githubusercontent.com/38724414/97124676-557ca300-1731-11eb-9aca-b949505a9847.jpg)

**Smartphone:**
 - Device: Samsung S8
 - OS: Android 9
 - Browser: DuckDuckGo
 - Version: 5.59.2 (55902)

**Comment by Pandraghon** [comment]
Fixed by: https://github.com/gw2ocs/gw2achievements/commit/d42638a191ffd791759868b8c60e85ece6c25883
